Resources:
  SlackLunchBotS3BucketAPILamba:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: slack-lunch-bot-api-lambda-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls : true
        BlockPublicPolicy : true
        IgnorePublicAcls : true
        RestrictPublicBuckets : true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
              - POST
              - PUT
              - DELETE
            AllowedOrigins:
              - "*"
